SECTION_TABLE_NAME = "perch-mount-376408.perch_mount_db.sections"
OCCURRENCE_TABLE_NAME = "perch-mount-376408.perch_mount_db.occurrence_test"
RAW_MEDIA_TABLE_NAME = "perch-mount-376408.perch_mount_db.raw_media_test"
PERCH_MOUNT_TABLE_NAME = "perch-mount-376408.perch_mount_db.perch_mount"

EMPTY_DES_DIR = "//Birdlab-Nas/棲架資料/棲架資料庫/空拍"

DATETIME_FROMAT = "%Y-%m-%d %H:%M:%S"
DATE_FROMAT = "%Y-%m-%d"

BIRD_SP_TAXON_ID = 35133

INDIVIDUAL_COL_NAME = (
    "taxon_order_by_ai",
    "taxon_order_by_human",
    "main_behavior_ch",
    "main_behavior_eng",
    "secondary_behavior_ch",
    "secondary_behavior_eng",
    "prey_ch",
    "prey_eng",
    "adult",
    "tagged",
    "transmitter",
    "xmin",
    "xmax",
    "ymin",
    "ymax",
    "featured",
)

MEDIUM_COL_NAME = (
    "medium_datetime",
    "medium_date",
    "object_id",
    "featured",
    "perch_mount_id",
    "perch_mount_name",
)


from datetime import datetime, timezone, date

occurrences = {
    "64168e9a697b9520481d2bd2": {
        "medium_datetime": datetime(2022, 4, 8, 13, 39, 30, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.1822,
                "xmax": 0.5762,
                "ymin": 0.3799,
                "ymax": 0.825,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080013.JPG",
    },
    "64168e9a697b9520481d2bd3": {
        "medium_datetime": datetime(2022, 4, 8, 13, 39, 30, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2208,
                "xmax": 0.4191,
                "ymin": 0.305,
                "ymax": 0.7706,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080014.JPG",
    },
    "64168e9a697b9520481d2bd4": {
        "medium_datetime": datetime(2022, 4, 8, 13, 39, 31, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2286,
                "xmax": 0.4278,
                "ymin": 0.3229,
                "ymax": 0.7287,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080015.JPG",
    },
    "64168e9a697b9520481d2bd7": {
        "medium_datetime": datetime(2022, 4, 8, 13, 44, 17, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2157,
                "xmax": 0.4279,
                "ymin": 0.3598,
                "ymax": 0.7176,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080018.JPG",
    },
    "64168e9a697b9520481d2bd6": {
        "medium_datetime": datetime(2022, 4, 8, 13, 44, 17, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2291,
                "xmax": 0.4241,
                "ymin": 0.4226,
                "ymax": 0.7194,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080017.JPG",
    },
    "64168e9a697b9520481d2bd8": {
        "medium_datetime": datetime(2022, 4, 8, 13, 44, 18, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2323,
                "xmax": 0.43,
                "ymin": 0.3405,
                "ymax": 0.7217,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080019.JPG",
    },
    "64168e9a697b9520481d2bda": {
        "medium_datetime": datetime(2022, 4, 8, 13, 52, 9, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2597,
                "xmax": 0.5305,
                "ymin": 0.3342,
                "ymax": 0.719,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080022.JPG",
    },
    "64168e9a697b9520481d2bdb": {
        "medium_datetime": datetime(2022, 4, 8, 13, 52, 9, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2459,
                "xmax": 0.4631,
                "ymin": 0.3095,
                "ymax": 0.8093,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080021.JPG",
    },
    "64168e9a697b9520481d2bdc": {
        "medium_datetime": datetime(2022, 4, 8, 13, 52, 10, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2595,
                "xmax": 0.5246,
                "ymin": 0.334,
                "ymax": 0.7122,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080023.JPG",
    },
    "64168e9a697b9520481d2bde": {
        "medium_datetime": datetime(2022, 4, 8, 13, 55, 38, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2193,
                "xmax": 0.5274,
                "ymin": 0.3258,
                "ymax": 0.8097,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080025.JPG",
    },
    "64168e9a697b9520481d2bdf": {
        "medium_datetime": datetime(2022, 4, 8, 13, 55, 38, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.225,
                "xmax": 0.4429,
                "ymin": 0.2888,
                "ymax": 0.8107,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080026.JPG",
    },
    "64168e9a697b9520481d2be0": {
        "medium_datetime": datetime(2022, 4, 8, 13, 55, 39, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2032,
                "xmax": 0.4464,
                "ymin": 0.2883,
                "ymax": 0.8262,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080027.JPG",
    },
    "64168e9a697b9520481d2be3": {
        "medium_datetime": datetime(2022, 4, 8, 13, 57, 22, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2292,
                "xmax": 0.4853,
                "ymin": 0.3486,
                "ymax": 0.7241,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草 鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080029.JPG",
    },
    "64168e9a697b9520481d2be2": {
        "medium_datetime": datetime(2022, 4, 8, 13, 57, 22, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2517,
                "xmax": 0.4617,
                "ymin": 0.3154,
                "ymax": 0.7878,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\# 棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080030.JPG",
    },
    "64168e9a697b9520481d2be4": {
        "medium_datetime": datetime(2022, 4, 8, 13, 57, 23, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2414,
                "xmax": 0.4558,
                "ymin": 0.389,
                "ymax": 0.7754,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080031.JPG",
    },
    "64168e9a697b9520481d2be7": {
        "medium_datetime": datetime(2022, 4, 8, 14, 7, 10, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2204,
                "xmax": 0.9339,
                "ymin": 0.3621,
                "ymax": 0.7609,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080033.JPG",
    },
    "64168e9a697b9520481d2be6": {
        "medium_datetime": datetime(2022, 4, 8, 14, 7, 10, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2253,
                "xmax": 0.5125,
                "ymin": 0.372,
                "ymax": 0.7072,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080034.JPG",
    },
    "64168e9a697b9520481d2be8": {
        "medium_datetime": datetime(2022, 4, 8, 14, 7, 11, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2283,
                "xmax": 0.4819,
                "ymin": 0.3122,
                "ymax": 0.7108,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080035.JPG",
    },
    "64168e9a697b9520481d2bea": {
        "medium_datetime": datetime(2022, 4, 8, 14, 12, 16, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2633,
                "xmax": 0.4726,
                "ymin": 0.3031,
                "ymax": 0.7617,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080037.JPG",
    },
    "64168e9a697b9520481d2beb": {
        "medium_datetime": datetime(2022, 4, 8, 14, 12, 16, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2646,
                "xmax": 0.4664,
                "ymin": 0.3108,
                "ymax": 0.7279,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080038.JPG",
    },
    "64168e9a697b9520481d2bec": {
        "medium_datetime": datetime(2022, 4, 8, 14, 12, 17, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2625,
                "xmax": 0.4616,
                "ymin": 0.3153,
                "ymax": 0.7293,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土 庫南側20220331-0409\\2022土庫南側04080039.JPG",
    },
    "64168e9a697b9520481d2bee": {
        "medium_datetime": datetime(2022, 4, 8, 14, 14, 17, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2702,
                "xmax": 0.5305,
                "ymin": 0.4195,
                "ymax": 0.7174,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\ 草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080041.JPG",
    },
    "64168e9a697b9520481d2bef": {
        "medium_datetime": datetime(2022, 4, 8, 14, 14, 17, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2657,
                "xmax": 0.5398,
                "ymin": 0.4062,
                "ymax": 0.7142,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080042.JPG",
    },
    "64168e9a697b9520481d2bf0": {
        "medium_datetime": datetime(2022, 4, 8, 14, 14, 18, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": 0.2664,
                "xmax": 0.5386,
                "ymin": 0.3998,
                "ymax": 0.7187,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080043.JPG",
    },
    "64168e9a697b9520481d2bd5": {
        "medium_datetime": datetime(2022, 4, 8, 13, 39, 32, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080016.MP4",
    },
    "64168e9a697b9520481d2bd9": {
        "medium_datetime": datetime(2022, 4, 8, 13, 44, 19, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080020.MP4",
    },
    "64168e9a697b9520481d2bdd": {
        "medium_datetime": datetime(2022, 4, 8, 13, 52, 11, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080024.MP4",
    },
    "64168e9a697b9520481d2be1": {
        "medium_datetime": datetime(2022, 4, 8, 13, 55, 40, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080028.MP4",
    },
    "64168e9a697b9520481d2be5": {
        "medium_datetime": datetime(2022, 4, 8, 13, 57, 24, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080032.MP4",
    },
    "64168e9a697b9520481d2be9": {
        "medium_datetime": datetime(2022, 4, 8, 14, 7, 12, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080036.MP4",
    },
    "64168e9a697b9520481d2bed": {
        "medium_datetime": datetime(2022, 4, 8, 14, 12, 18, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022土庫南側04080040.MP4",
    },
    "64168e9a697b9520481d2bf1": {
        "medium_datetime": datetime(2022, 4, 8, 14, 14, 19, tzinfo=timezone.utc),
        "medium_date": date(2022, 4, 8),
        "individual": [
            {
                "taxon_order_by_ai": 7575,
                "taxon_order_by_human": None,
                "perch_mount_id": 3,
                "perch_mount_name": "土庫南側",
                "main_behavior_ch": None,
                "main_behavior_eng": None,
                "secondary_behavior_ch": None,
                "secondary_behavior_eng": None,
                "prey_ch": None,
                "prey_eng": None,
                "adult": None,
                "tagged": None,
                "transmitter": None,
                "xmin": None,
                "xmax": None,
                "ymin": None,
                "ymax": None,
                "featured": None,
                "chinese_common_name_ai": "黑翅鳶",
                "chinese_common_name_human": None,
            }
        ],
        "path": "\\\\Birdlab-Nas\\棲架資料\\#棲架資料已備份\\草鴞棲架\\土庫\\土庫南側20220331-0409\\2022 土庫南側04080044.MP4",
    },
}
